version: '3.4'

services:
  api:
    build: ./app
    container_name: api
    networks:
      - default
    volumes:
      - ./app/:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "5000:5000"
    env_file:
      - .env

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"
    networks:
      - default

  front:
    build: ./front
    container_name: front
    networks:
      - default
    ports:
      - "8050:8050"
    depends_on:
      - keycloak
  
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ['start-dev', "--http-relative-path=/auth"]
    networks:
      - default